# created by huzongyao
name: GitHub Pages Deploy

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - main # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      # 安装python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 生成静态文件
      - name: Build Vue
        run: npm install && npm run build

      # 生成Plist文件
      - name: Generate Plist
        run: |
          python main.py

      # 部署到 GitHub Pages
      #ACCESS_TOKEN
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          node-version: '14.x'
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
